name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.9
        with:
          method: "universal"
          client-id: "${{ secrets.CLIENT_ID }}"
          client-secret: "${{ secrets.CLIENT_SECRET }}"
          identity-id: "09a0eecd-f311-49c8-9eea-5f930a42c5b7"
          domain: "https://app.infisical.com" # Update to the instance URL when using EU (https://eu.infisical.com), a dedicated instance, or a self-hosted instance
          env-slug: "prod"
          project-slug: "portfolio-site-gha-egv6"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Upload to Cloud Storage"
        run: |
          gsutil -m rsync -d -c -r dist gs://${{ secrets.GCP_BUCKET_NAME }}

      - name: "Purge Fastly Cache via API"
        run: |
          curl -X POST -H "Fastly-Key: ${{ secrets.FASTLY_API_TOKEN }}" \
               "https://api.fastly.com/service/${{ secrets.FASTLY_SID }}/purge_all"